title: Dan Greenhill # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A dedicated, analytically driven and enthusiastic Mathematics BSc(Hons) Graduate of Nottingham Trent University and Equities Trader.
  <br><br>
  Currently employed as a Data Analyst.
  <br><br>
  •Degree-level user of <b>Microsoft Excel, MATLAB</b> and <b>R</b>.
  <br>
  •Profcient in <b>SQL</b>.
  <br>
  •Actively learning <b>Python</b>.
  <br>
  •Experience in <b>Minitab, LaTeX, Tableau</b> and <b>Dell Statistica</b>.
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/dan-greenhill-711b3a107/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
