title: Dan Greenhill # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A dedicated, analytically driven and enthusiastic Mathematics BSc(Hons) Graduate of Nottingham Trent University.
  <br>
  Currently Self-Employed as an Equities Trader.
  <br><br>
  •Degree-level user of <b>Microsoft Excel, MATLAB</b> and <b>R</b>.
  <br>
  •Actively learning <b>SQL</b>, <b>Tableau</b> and <b>Python</b>.
  <br>
  •Experience in <b>Minitab, LaTeX</b> and <b>Dell Statistica</b>.
  <br><br>
  I am looking to build on the skills and experience 
  I have acquired to date and successfully apply these in an Analyst role with a view to progress in this field.
  <br><br>
  <a href="https://www.linkedin.com/in/dan-greenhill-711b3a107/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
